"""
: mastermind.py
: created by Andy Dolinski
: 21 September 2013

: Rules: A random sequence of coloured pins are generated by the computer.
: The player has to guess the correct sequence within 12 attempts.  The game
: will inform the player how many coloured pins they have guessed correctly
: and how many pins are in the correct place.

"""
import random
#from copy import copy

"""
R: Red   G: Green   B: Blue   Y: Yellow    W: White    O: Orange
"""
COLOURS = ['R', 'G', 'B', 'Y', 'W', 'O']
MAXATTEMPTS = 12


def title():
    """
    Function:
        Used to print the title for the Mastermind game.

        Args: None.
        Returns: None.
    """

    print("""
___  ___          _                      _           _
|  \/  |         | |                    (_)         | |
| .  . | __ _ ___| |_ ___ _ __ _ __ ___  _ _ __   __| |
| |\/| |/ _` / __| __/ _ \ '__| '_ ` _ \| | '_ \ / _` |
| |  | | (_| \__ \ ||  __/ |  | | | | | | | | | | (_| |
\_|  |_/\__,_|___/\__\___|_|  |_| |_| |_|_|_| |_|\__,_|

          """)


def rules():
    """
    Function:
        Used to print the rules of the game.

        Args: None.
        Returns: None.
    """

    print("""
Rules:
------
A random sequence of coloured pins have been generated by the computer.
You have to guess the correct sequence within 12 attempts.  The game
will inform you of how many coloured pins you have guessed correctly
and how many pins are in the correct place.
""")


def setupGame():
    """
    Function:
        Used to set up the game.

        Args: None.
        Returns: The sequence to be guessed by the player.
    """

    coloursTemp = ['R', 'G', 'B', 'Y', 'W', 'O']
    sequence = []

    for i in range(0, 4):
        # choose random position in the colours list
        randomColour = random.randint(0, len(coloursTemp)-1)
        # select colour
        sequence += coloursTemp[randomColour]
        # remove colour from list
        coloursTemp.pop(randomColour)

    print(sequence)

    return sequence


def getInput():
    """
    Function:
        Gets player input and returns answer as a formatted list.

        Args: None.
        Returns: playerInput
    """

    print("""
--------------------------
| R: Red     | B: Blue   |
| G: Green   | W: White  |
| Y: Yellow  | O: Orange |
--------------------------
Sequence example: XXXX

""")
    playerInput = input("Enter your sequence: ")

    return playerInput


def checkSequence(playerInput, sequence):
    """
    Function:
        Checks the player's input against the sequence. Returns the result of
        the player's guess in terms of how many colour pins they have correctly
        guessed and how many of those pins are in the correct location.

        Args: playerInput
        Returns: A boolean variable winner that ends the game if the player
                 has correctly guessed the sequence.
    """
    correctPosition = 0
    correctColours = 0
    tempColourCheck = []
    tempColourCheck += sequence

    # Check the number of colours in the correct position.
    for i in range(0, 4):
        # compare sequence with playerInput and increase ccorrectPosition count
        # if the current colour is correct and in the right position.
        if playerInput[i] == sequence[i]:
            correctPosition += 1

        # if the current colour being checked is in the sequence, increase
        # correctColours count and remove it from tempColourCheck list.
        if playerInput[i] in tempColourCheck:
            correctColours += 1
            toRemove = playerInput[i]
            tempColourCheck.remove(toRemove)

    # print the results of the player's guess.
    if correctPosition < 4:
        print("--------------------------\n")
        if correctColours == 0:
            print("The colours you have chosen are not in the sequence.")
            print("\n")
        elif correctColours == correctPosition:
            print("You have correctly identified %i colour(s) in the "
                  "correct position" % correctPosition)
            print("but no other colours have been correctly identified.")
            print("\n")
        elif correctColours > 0 and correctPosition == 0:
            print("You have %i colour(s) correctly identified" %
                  correctColours)
            print("but none are in the correct position.")
            print("\n")
        else:
            print("You have %i colour(s) in the correct location and" %
                  correctPosition)
            print("you have correctly guessed %i of the colours." %
                  correctColours)
            print("\n")
        winner = False
    else:
        print("You correctly guessed the sequence: ", ''.join(sequence))
        winner = True

    return winner

def game():
    # Begin game
    title()
    rules()
    sequence = setupGame()
    attempts = 0

    while attempts < MAXATTEMPTS:

        # initialised at 4 to enter loop and reset back to 0 when loop entered
        invalidLetter = 4

        # establish whether we have a valid input from the player
        while invalidLetter > 0:

            invalidLetter = 0

            playerInput = getInput()
            playerInput = list(playerInput.upper())

            if len(playerInput) == 4:

                for letter in playerInput:
                    if letter not in COLOURS:
                        invalidLetter += 1

                if invalidLetter > 0:
                    print("\nYou didn't enter a valid sequence of letters.")
                    print("Number of bad letters: ", invalidLetter)

            else:
                print("\nYou must enter four letters for each sequence.")
                print("You only entered", len(playerInput), "letter(s).\n\n")
                invalidLetter = 4

        # player has entered a valid sequence
        winner = checkSequence(playerInput, sequence)
        attempts += 1

        if winner is False:
            if attempts == 11:
                print("You have", MAXATTEMPTS - attempts, "attempt left.")
            else:
                print("You have", MAXATTEMPTS - attempts, "attempts left.")
        else:
            if attempts == 1:
                print("\nYou won the game in", attempts, "attempt")
            else:
                print("\nYou won the game in", attempts, "attempts")
            attempts = MAXATTEMPTS

    if winner is False:
        print("You failed to guess the correct sequence.")
        print("The sequence was: ", ''.join(sequence), sep='')

    print("\n\nThank you for playing\n\n")

    title()

    print("\n\n\n")
    input("Press enter to exit...")


game()
